# Generated by Django 5.2.17 on 2026-09-11 05:40

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_postgis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('weights_path', models.CharField(max_length=500)),
                ('framework', models.CharField(max_length=50)),
                ('input_size', models.IntegerField()),
                ('tile_size', models.IntegerField()),
                ('overlap_ratio', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.frame_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude_m', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('queued', 'Kuyrukta'), ('processing', 'Isleniyor'), ('done', 'Tamam'), ('failed', 'Basarisiz')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='core.mission')),
            ],
        ),
        migrations.CreateModel(
            name='InferenceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_threshold', models.FloatField()),
                ('iou_threshold', models.FloatField()),
                ('tile_size', models.IntegerField()),
                ('overlap_ratio', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('running', 'Calisiyor'), ('done', 'Tamam'), ('failed', 'Basarisiz')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('frames_total', models.IntegerField(default=0)),
                ('frames_done', models.IntegerField(default=0)),
                ('frames_failed', models.IntegerField(default=0)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.mission')),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='core.modelversion')),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('x1', models.IntegerField()),
                ('y1', models.IntegerField()),
                ('x2', models.IntegerField()),
                ('y2', models.IntegerField()),
                ('tile_row', models.IntegerField(blank=True, null=True)),
                ('tile_col', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='core.frame')),
                ('inference_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='core.inferencerun')),
            ],
            options={
                'indexes': [models.Index(fields=['inference_run', '-score'], name='detection_run_score_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='frame',
            index=models.Index(fields=['mission', 'status'], name='frame_mission_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='frame',
            constraint=models.UniqueConstraint(fields=('mission', 'sha256'), name='uniq_frame_sha256_per_mission'),
        ),
    ]
