# Generated by Django 5.2.17 on 2026-09-12 21:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_model512_onnx_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('accepted', 'Dogrulandi'), ('rejected', 'Reddedildi'), ('uncertain', 'Belirsiz')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.detection')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('location_source', models.CharField(choices=[('none', 'Konum yok'), ('exif', 'Goruntu EXIF GPS'), ('flight_log', 'Ucus gunlugu'), ('manual', 'Operator girisi'), ('demo', 'Demo / sentetik')], default='none', max_length=20)),
                ('location_note', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('candidate', 'Aday'), ('confirmed', 'Dogrulandi'), ('dismissed', 'Elendi')], default='candidate', max_length=20)),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
                ('cluster_key', models.CharField(blank=True, max_length=100)),
                ('clustered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to=settings.AUTH_USER_MODEL)),
                ('detection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='core.detection')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.mission')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='core.review')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('member_added', 'Uye eklendi'), ('member_role_changed', 'Uye rolu degisti'), ('member_removed', 'Uye cikarildi'), ('review_created', 'Inceleme olusturuldu'), ('review_updated', 'Inceleme guncellendi'), ('finding_created', 'Bulgu olusturuldu'), ('finding_updated', 'Bulgu guncellendi'), ('finding_deleted', 'Bulgu silindi'), ('cluster_run', 'Kumeleme calistirildi'), ('run_started', 'Tarama baslatildi')], max_length=40)),
                ('object_type', models.CharField(max_length=40)),
                ('object_id', models.CharField(blank=True, max_length=40)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='core.mission')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['mission', '-created_at'], name='audit_mission_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='MissionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Sahip'), ('operator', 'Operator'), ('viewer', 'Izleyici')], default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_mission_members', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'mission'], name='mission_member_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('mission', 'user'), name='uniq_mission_member')],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['detection', 'decision'], name='review_detection_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('detection', 'reviewer'), name='uniq_review_per_reviewer'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['mission', 'status'], name='finding_mission_status_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['mission', 'cluster_key'], name='finding_cluster_idx'),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('location__isnull', True), ('location_source', 'none')), models.Q(('location__isnull', False), models.Q(('location_source', 'none'), _negated=True)), _connector='OR'), name='finding_konum_kaynak_tutarli'),
        ),
    ]
